### ISSUE TITLE
Getting KeyError in gscout.py

### ISSUE THREAD

**Issue by shivankar-madaan** [nccgroup/G-Scout#4]
I just did the setup as the README and got this error

```
master $ python gscout.py  "project" "decent-oxygen-188712"
Traceback (most recent call last):
  File "gscout.py", line 61, in <module>
    list_projects(sys.argv[1],sys.argv[2])
  File "gscout.py", line 33, in list_projects
    for project in response['projects']:
KeyError: 'projects'
```

Is that I am doing something wrong somewhere?
I have created these projects as well

```
master $ gcloud projects list
PROJECT_ID                             NAME         PROJECT_NUMBER
decent-oxygen-188712                   test         789585268386
my-project-1481904208488               My Project   978641422651
```

**Comment by lgap** [comment]
This might be a missing permission issue:
Do you have both the:
1. Security Reviewer permissions
2. Viewer permissions 
for the service account in these projects?

**Comment by shivankar-madaan** [comment]
I have the owner permission for the service account,would it work in this case?

**Comment by lgap** [comment]
It is best practice to use service-accounts for scripts with least-privilege. 
Does creating the service account with both permissions work for you?

**Comment by shivankar-madaan** [comment]
Let me try and update you on this
