### ISSUE TITLE
Failed to Fetch

### ISSUE THREAD

**Issue by sanjogpandasp** [nccgroup/G-Scout#8]
I have followed the README.md have created a service account with Security Reviewer and Viewer access but while running the scan I get the below output

> (gscout) Sanjogs-MacBook-Pro:G-Scout sanjogpanda$ python gscout.py --project "infra*"
> /Users/sanjogpanda/Envs/gscout/lib/python2.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access creds.data: No such file or directory
>   warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
> ('Scouting ', u'infra')
> Failed to fetch roles.
> Failed to fetch service accounts.
> Failed to fetch SQL instances.

I understand the 3rd line ie. Failed to fetch SQL instances.

But I am not sure why G-Scout is not able to scan service accounts and roles

```
Failed to fetch roles.
Failed to fetch service accounts.
```

Could anyone please help me understand where I am going wrong?

**Comment by angelomellos** [comment]
I believe this will now be fixed since it will use the client library properly for everything, which was not quite the case before.

**Comment by nycnewman** [comment]
Just FYI but found a fork of your code that solves this. It appears the default code path in your fork assumes a creds.data file has authentication key and never goes through workflow to generate if empty. A separate fork changed this around and key is correctly created. 

Is there an assumption on how creds and retrieve and generated that is not documented somewhere?
